project:
  type: website

website:
  title: "EOTC Dallas Area"
  sidebar:
    title: "EOTC St Michael and St Slassie YouTube Channels"
    style: "docked"
    search: true
    logo: images/logo.png
  
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true



